import '../styles/global.scss';
import type { Metadata } from 'next';
import GlobalProvider from 'components/unlisted/GlobalProvider';
import Site from '../components/unlisted/Site';
import type { Link } from '../data/types/link.types';
import { draftMode } from 'next/headers';
import DraftModeBanner from '../components/utils/draft-mode-banner/DraftModeBanner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled: draftEnabled } = draftMode();

  // todo global site settings from prepr?
  const siteSettings = {
    menuLinks: [
      {
        text: 'home',
        linkType: 'internal',
        url: '/',
      },
      {
        text: 'about',
        linkType: 'internal',
        url: '/about',
      },
    ] as Array<Link>,
  };

  return (
    <html lang="en">
      <body>
        <GlobalProvider siteSettingsData={siteSettings}>
          <Site>{children}</Site>
          {draftEnabled && <DraftModeBanner />}
        </GlobalProvider>
      </body>
    </html>
  );
}
