import '../styles/global.scss';
import type { Metadata } from 'next';
import GlobalProvider from 'components/unlisted/GlobalProvider';
import Site from '../components/unlisted/Site';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteSettings = {};
  return (
    <html lang="en">
      <body>
        <GlobalProvider siteSettingsData={siteSettings}>
          <Site>{children}</Site>
        </GlobalProvider>
      </body>
    </html>
  );
}
